---
title: "cleanweather"
output: html_document
---
```{r}

```

cleaned weather so that it is just columns from 2023, now named "cleanedbikesweather.csv"

```{r}
cleanedbikesweather$dew <- NULL
View(cleanedbikesweather)
```

Deleted dew column from cleanedbikesweather

```{r}
cleanedbikesweather$feelslike <- NULL
cleanedbikesweather$feelslikemin <- NULL
cleanedbikesweather$feelslikemax <- NULL
cleanedbikesweather$snow <- NULL
cleanedbikesweather$snowdepth <- NULL
cleanedbikesweather$solarradiation <- NULL
cleanedbikesweather$solarenergy <- NULL
cleanedbikesweather$windgust <- NULL
cleanedbikesweather$windspeed <- NULL
cleanedbikesweather$winddir <- NULL
cleanedbikesweather$sealevelpressure <- NULL
cleanedbikesweather$severerisk <- NULL
cleanedbikesweather$name <- NULL
cleanedbikesweather$precipprob <- NULL
View(cleanedbikesweather)
```

```{r}
write.csv(cleanedbikesweather, file = "cleanedbikesweather.csv")
```


```{r}
library(ggplot2)
ggplot(cleanedbikesweather, aes(precip, humidity)) +geom_point()
```
```{r}
View(202301-capitalbikeshare-tripdata)
data <- read.csv("202301-capitalbikeshare-tripdata.csv")
```

```{r}
old_name <- "202301-capitalbikeshare-tripdata.csv"  
new_name <- "janbikedata.csv"
```

```{r}
janbikedata$ride_id <- NULL
janbikedata$rideable_type <- NULL
janbikedata$member_casual <- NULL
View(janbikedata)
```

```{r}
write.csv(janbikedata.csv, file = "janbikedataclean")
```
```{r}

library(dplyr)
library(lubridate)

data <- read.csv("janbikedataclean.csv")                                                                                                                                                                                                    

data$started_at <- ymd_hms(data$started_at)  
data$ended_at <- ymd_hms(data$ended_at)    


data <- data %>%
  mutate(time_difference = as.numeric(difftime(ended_at, started_at, units = "mins")))

print(head(data))

write.csv(data, "janbikedataclean_updated.csv", row.names = FALSE)
```



```{r}
febbikedata$ride_id <- NULL
febbikedata$rideable_type <- NULL
febbikedata$member_casual <- NULL
View(febbikedata)

```

```{r}
marbikedata$ride_id <- NULL
marbikedata$rideable_type <- NULL
marbikedata$member_casual <- NULL
View(marbikedata.csv)

write.csv(marbikedata, file = "marbikedataclean.csv")

```

```{r}
library(dplyr)
library(lubridate)

data <- read.csv("marbikedataclean.csv")                                                                                                                                                                                                    

data$started_at <- ymd_hms(data$started_at)  
data$ended_at <- ymd_hms(data$ended_at)    


data <- data %>%
  mutate(time_difference = as.numeric(difftime(ended_at, started_at, units = "mins")))

print(head(data))

write.csv(data, "marbikedataclean_updated.csv", row.names = FALSE)
```

```{r}
aprilbikedata$ride_id <- NULL
aprilbikedata$rideable_type <- NULL
aprilbikedata$member_casual <- NULL
View(aprilbikedata)

write.csv(aprilbikedata, file = "aprilbikedataclean.csv")
```

```{r}
library(dplyr)
library(lubridate)

data <- read.csv("aprilbikedataclean.csv")                                                                                                                                                                                                    

data$started_at <- ymd_hms(data$started_at)  
data$ended_at <- ymd_hms(data$ended_at)    


data <- data %>%
  mutate(time_difference = as.numeric(difftime(ended_at, started_at, units = "mins")))

print(head(data))

write.csv(data, "aprilbikedataclean_updated.csv", row.names = FALSE)
```


```{r}
maybikedata$ride_id <- NULL
maybikedata$rideable_type <- NULL
maybikedata$member_casual <- NULL
maybikedata$start_lat <- NULL
maybikedata$end_lat <- NULL
maybikedata$start_lng <- NULL
maybikedata$end_lng <- NULL
View(maybikedata)

write.csv(maybikedata, file = "maybikedataclean.csv")
```

```{r}
library(dplyr)
library(lubridate)

data <- read.csv("maybikedataclean.csv")                                                                                                                                                                                                    

data$started_at <- ymd_hms(data$started_at)  
data$ended_at <- ymd_hms(data$ended_at)    


data <- data %>%
  mutate(time_difference = as.numeric(difftime(ended_at, started_at, units = "mins")))

print(head(data))

write.csv(data, "maybikedataclean_updated.csv", row.names = FALSE)
```


```{r}
junebikedata$ride_id <- NULL
junebikedata$rideable_type <- NULL
junebikedata$member_casual <- NULL
junebikedata$start_lat <- NULL
junebikedata$end_lat <- NULL
junebikedata$start_lng <- NULL
junebikedata$end_lng <- NULL


write.csv(junebikedata, file = "junebikedataclean.csv")
```

```{r}
library(dplyr)
library(lubridate)

data <- read.csv("junebikedataclean.csv")                                                                                                                                                                                                    

data$started_at <- ymd_hms(data$started_at)  
data$ended_at <- ymd_hms(data$ended_at)    


data <- data %>%
  mutate(time_difference = as.numeric(difftime(ended_at, started_at, units = "mins")))

print(head(data))

write.csv(data, "junebikedataclean_updated.csv", row.names = FALSE)
```


```{r}
julybikedata$ride_id <- NULL
julybikedata$rideable_type <- NULL
julybikedata$member_casual <- NULL
julybikedata$start_lat <- NULL
julybikedata$end_lat <- NULL
julybikedata$start_lng <- NULL
julybikedata$end_lng <- NULL


write.csv(julybikedata, file = "julybikedataclean.csv")
```

```{r}
augbikedata$ride_id <- NULL
augbikedata$rideable_type <- NULL
augbikedata$member_casual <- NULL
View(augbikedata)

write.csv(augbikedata, file= "~/BIO185Evs/augbikedataclean.csv")
```

```{r}
septbikedata$ride_id <- NULL
septbikedata$rideable_type <- NULL
septbikedata$member_casual <- NULL
View(septbikedata)

write.csv(septbikedata, file= "~/BIO185Evs/septbikedataclean.csv")
```

```{r}
octbikedata$ride_id <- NULL
octbikedata$rideable_type <- NULL
octbikedata$member_casual <- NULL
View(octbikedata)

write.csv(octbikedata, file= "~/BIO185Evs/octbikedataclean.csv")
```

```{r}
novbikedata$ride_id <- NULL
novbikedata$rideable_type <- NULL
novbikedata$member_casual <- NULL
View(novbikedata)

write.csv(novbikedata, file= "~/BIO185Evs/novbikedataclean.csv")
```

```{r}
decbikedata$ride_id <- NULL
decbikedata$rideable_type <- NULL
decbikedata$member_casual <- NULL
View(decbikedata)

write.csv(decbikedata, file= "~/BIO185Evs/decbikedataclean.csv")
```
 

```{r}
library(dplyr)
library(lubridate)

data <- read.csv("febbikedataclean.csv")                                                                                                                                                                                                    

data$started_at <- ymd_hms(data$started_at)  
data$ended_at <- ymd_hms(data$ended_at)    


data <- data %>%
  mutate(time_difference = as.numeric(difftime(ended_at, started_at, units = "mins")))

print(head(data))

write.csv(data, "febbikedataclean_updated.csv", row.names = FALSE)

```



