---
title: "Untitled"
output: html_document
---


take all the months and combine them to make a year
```{r}
year_average_timedif <- rbind(janaverage_by_day, febaverage_by_day, maraverage_by_day, aprilaverage_by_day, mayaverage_by_day, juneaverage_by_day, julyaverage_by_day, augaverage_by_day, septaverage_by_day, octaverage_by_day, novaverage_by_day, decaverage_by_day)
          

write.csv(year_average_timedif, "year_average_timedif.csv", row.names=TRUE)
```


merging so that I have the bike ride time and the weather in the same file to work with


```{r}
merge_data <- data.frame(Date= cleanedbikesweather$datetime, Duration = year_average_timedif$avg_time_diff, Tempmax = cleanedbikesweather$tempmax, Tempmin= cleanedbikesweather$tempmin, Tempavg= cleanedbikesweather$temp, Humidity = cleanedbikesweather$humidity, Precip = cleanedbikesweather$precip, Preciptype = cleanedbikesweather$preciptype, Cloudcover= cleanedbikesweather$cloudcover, UV= cleanedbikesweather$uvindex, Moonphase= cleanedbikesweather$moonphase, Conditions= cleanedbikesweather$conditions, Conditionsdescription= cleanedbikesweather$description, Icon= cleanedbikesweather$icon)

write.csv(merge_data, "merged_weather_data.csv", row.names = FALSE)
```




