---
title: "frequently_used_stations"
output: html_document
---

#Determining what stations are used most frequently


```{r}

library(tidyverse)

```



#202301 frequency

```{r}

tripdata_202301 <- readRDS("monthly-data/janbikedata.rds")
 station_counts <- tripdata_202301 %>%
   count(start_station_name, sort = TRUE)
 saveRDS(station_counts, file = "202301_station_freq.rds")
 
 
```


#202302 frequency

```{r}

tripdata_202302 <- readRDS("monthly-data/febbikedata.rds")
 station_counts <- tripdata_202302 %>%
   count(start_station_name, sort = TRUE)
 saveRDS(station_counts, file = "202302_station_freq.rds")
 
```


#202303 frequency

```{r}

tripdata_202303 <- readRDS("monthly-data/marbikedata.rds")
 station_counts <- tripdata_202303 %>%
   count(start_station_name, sort = TRUE)
 saveRDS(station_counts, file = "202303_station_freq.rds")

```


#202304 frequency

```{r}

tripdata_202304 <- readRDS("monthly-data/aprilbikedata.rds")
 station_counts <- tripdata_202304 %>%
   count(start_station_name, sort = TRUE)
 saveRDS(station_counts, file = "202304_station_freq.rds")

```



#202305 frequency

```{r}

tripdata_202305 <- readRDS("monthly-data/maybikedata.rds")
 station_counts <- tripdata_202305 %>%
   count(start_station_name, sort = TRUE)
 saveRDS(station_counts, file = "202305_station_freq.rds")

```


#202306 frequency

```{r}

tripdata_202306 <- readRDS("monthly-data/junebikedata.rds")
 station_counts <- tripdata_202306 %>%
   count(start_station_name, sort = TRUE)
 saveRDS(station_counts, file = "202306_station_freq.rds")

```


#202307 frequency

```{r}

tripdata_202307 <- readRDS("monthly-data/julybikedata.rds")
 station_counts <- tripdata_202307 %>%
   count(start_station_name, sort = TRUE)
 saveRDS(station_counts, file = "202307_station_freq.rds")

```


#202308 frequency

```{r}

tripdata_202308 <- readRDS("monthly-data/augbikedata.rds")
 station_counts <- tripdata_202308 %>%
   count(start_station_name, sort = TRUE)
 saveRDS(station_counts, file = "202308_station_freq.rds")

```


#202309 frequency

```{r}

tripdata_202309 <- readRDS("monthly-data/septbikedata.rds")
 station_counts <- tripdata_202309 %>%
   count(start_station_name, sort = TRUE)
 saveRDS(station_counts, file = "202309_station_freq.rds")

```


#202310 frequency

```{r}

tripdata_202310 <- readRDS("monthly-data/octbikedata.rds")
 station_counts <- tripdata_202310 %>%
   count(start_station_name, sort = TRUE)
 saveRDS(station_counts, file = "202310_station_freq.rds")

```


#202311 frequency

```{r}

tripdata_202311 <- readRDS("monthly-data/novbikedata.rds")
 station_counts <- tripdata_202311 %>%
   count(start_station_name, sort = TRUE)
 saveRDS(station_counts, file = "202311_station_freq.rds")

```


#202312 frequency

```{r}

tripdata_202312 <- readRDS("monthly-data/decbikedata.rds")
 station_counts <- tripdata_202312 %>%
   count(start_station_name, sort = TRUE)
 saveRDS(station_counts, file = "202312_station_freq.rds")

```









